// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pylae.Data.Context;

#nullable disable

namespace Pylae.Data.Migrations.Visits
{
    [DbContext(typeof(PylaeVisitsDbContext))]
    partial class PylaeVisitsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Pylae.Data.Entities.Visits.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberBusinessIdNumber")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberBusinessRank")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberFirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MemberIsPermanentStaff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemberLastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemberOfficeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberPersonalIdNumber")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberTypeCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkstationId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("MemberNumber", "TimestampUtc");

                    b.HasIndex("SiteCode", "TimestampUtc");

                    b.ToTable("Visits", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
