using Pylae.Core.Models;
using Pylae.Desktop.ViewModels;

namespace Pylae.Desktop.Forms;

public partial class MemberTypeEditorForm : Form
{
    private readonly CatalogsViewModel _viewModel;
    private MemberType _memberType = new();

    public MemberTypeEditorForm(CatalogsViewModel viewModel)
    {
        _viewModel = viewModel;
        InitializeComponent();
    }

    public void LoadMemberType(MemberType memberType)
    {
        _memberType = memberType;
        nameText.Text = memberType.DisplayName;
        descriptionText.Text = memberType.Description;
        displayOrderNumeric.Value = memberType.DisplayOrder;
        isActiveCheck.Checked = memberType.IsActive;
    }

    private async void OnSaveClick(object sender, EventArgs e)
    {
        if (string.IsNullOrWhiteSpace(nameText.Text))
        {
            MessageBox.Show("Display name is required.", Text, MessageBoxButtons.OK, MessageBoxIcon.Warning);
            return;
        }

        _memberType.DisplayName = nameText.Text.Trim();
        _memberType.Description = descriptionText.Text.Trim();
        _memberType.DisplayOrder = (int)displayOrderNumeric.Value;
        _memberType.IsActive = isActiveCheck.Checked;
        // Code is auto-generated by the service from DisplayName

        await _viewModel.SaveMemberTypeAsync(_memberType);
        DialogResult = DialogResult.OK;
        Close();
    }

    private void OnCancelClick(object sender, EventArgs e)
    {
        DialogResult = DialogResult.Cancel;
        Close();
    }
}
