//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pylae.Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pylae.Desktop.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated..
        /// </summary>
        internal static string Account_PasswordUpdated {
            get {
                return ResourceManager.GetString("Account_PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick code is not allowed for shared or admin accounts..
        /// </summary>
        internal static string Account_QuickCodeNotAllowed {
            get {
                return ResourceManager.GetString("Account_QuickCodeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick code updated..
        /// </summary>
        internal static string Account_QuickCodeUpdated {
            get {
                return ResourceManager.GetString("Account_QuickCodeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gate &amp; Reception Control.
        /// </summary>
        internal static string App_Subtitle {
            get {
                return ResourceManager.GetString("App_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pylae.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not authenticated..
        /// </summary>
        internal static string App_UserNotAuthenticated {
            get {
                return ResourceManager.GetString("App_UserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup operation failed..
        /// </summary>
        internal static string Backup_Failed {
            get {
                return ResourceManager.GetString("Backup_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup package is invalid or incomplete..
        /// </summary>
        internal static string Backup_Invalid {
            get {
                return ResourceManager.GetString("Backup_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup failed verification: {0}.
        /// </summary>
        internal static string Backup_InvalidDetail {
            get {
                return ResourceManager.GetString("Backup_InvalidDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum mismatch for restored databases..
        /// </summary>
        internal static string Backup_ReasonChecksumMismatch {
            get {
                return ResourceManager.GetString("Backup_ReasonChecksumMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored database file is empty..
        /// </summary>
        internal static string Backup_ReasonEmptyDb {
            get {
                return ResourceManager.GetString("Backup_ReasonEmptyDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing master or visits database after restore..
        /// </summary>
        internal static string Backup_ReasonMissingDb {
            get {
                return ResourceManager.GetString("Backup_ReasonMissingDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest not found or incomplete..
        /// </summary>
        internal static string Backup_ReasonNoManifest {
            get {
                return ResourceManager.GetString("Backup_ReasonNoManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore completed. Restart now?.
        /// </summary>
        internal static string Backup_RestartPrompt {
            get {
                return ResourceManager.GetString("Backup_RestartPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore will overwrite local databases and photos. Continue?.
        /// </summary>
        internal static string Backup_RestoreConfirm {
            get {
                return ResourceManager.GetString("Backup_RestoreConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup restored. Please restart the app..
        /// </summary>
        internal static string Backup_Restored {
            get {
                return ResourceManager.GetString("Backup_Restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup created..
        /// </summary>
        internal static string Backup_Saved {
            get {
                return ResourceManager.GetString("Backup_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge PDF saved..
        /// </summary>
        internal static string Badge_PdfSaved {
            get {
                return ResourceManager.GetString("Badge_PdfSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing failed. Please open the PDF and print manually..
        /// </summary>
        internal static string Badge_PrintFailed {
            get {
                return ResourceManager.GetString("Badge_PrintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge ready for printing..
        /// </summary>
        internal static string Badge_PrintReady {
            get {
                return ResourceManager.GetString("Badge_PrintReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit.
        /// </summary>
        internal static string Button_AddEdit {
            get {
                return ResourceManager.GetString("Button_AddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        internal static string Button_AddUser {
            get {
                return ResourceManager.GetString("Button_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string Button_Backup {
            get {
                return ResourceManager.GetString("Button_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge PDF.
        /// </summary>
        internal static string Button_BadgePdf {
            get {
                return ResourceManager.GetString("Button_BadgePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogs.
        /// </summary>
        internal static string Button_Catalogs {
            get {
                return ResourceManager.GetString("Button_Catalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string Button_ChangePassword {
            get {
                return ResourceManager.GetString("Button_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change quick code.
        /// </summary>
        internal static string Button_ChangeQuickCode {
            get {
                return ResourceManager.GetString("Button_ChangeQuickCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string Button_Deactivate {
            get {
                return ResourceManager.GetString("Button_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string Button_EditUser {
            get {
                return ResourceManager.GetString("Button_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Button_Filter {
            get {
                return ResourceManager.GetString("Button_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print badge.
        /// </summary>
        internal static string Button_PrintBadge {
            get {
                return ResourceManager.GetString("Button_PrintBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Sites.
        /// </summary>
        internal static string Button_RemoteSites {
            get {
                return ResourceManager.GetString("Button_RemoteSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string Button_ResetPassword {
            get {
                return ResourceManager.GetString("Button_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick code.
        /// </summary>
        internal static string Button_ResetQuickCode {
            get {
                return ResourceManager.GetString("Button_ResetQuickCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Button_Restore {
            get {
                return ResourceManager.GetString("Button_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch user.
        /// </summary>
        internal static string Button_SwitchUser {
            get {
                return ResourceManager.GetString("Button_SwitchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string Button_Unlock {
            get {
                return ResourceManager.GetString("Button_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database password is required to continue..
        /// </summary>
        internal static string DbPassword_Cancelled {
            get {
                return ResourceManager.GetString("DbPassword_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found existing database for site: &apos;{0}&apos;
        ///
        ///Would you like to use this existing database?
        ///
        ///Click YES to use existing database (you&apos;ll need the encryption password)
        ///Click NO to start fresh with first-run setup.
        /// </summary>
        internal static string DbPassword_DiscoveryMessage {
            get {
                return ResourceManager.GetString("DbPassword_DiscoveryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Database Found.
        /// </summary>
        internal static string DbPassword_DiscoveryTitle {
            get {
                return ResourceManager.GetString("DbPassword_DiscoveryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum password attempts reached.
        ///
        ///Would you like to start with first-run setup instead?
        ///
        ///WARNING: Starting fresh will create a new database and you won&apos;t be able to access the existing data without the correct password..
        /// </summary>
        internal static string DbPassword_MaxAttemptsReached {
            get {
                return ResourceManager.GetString("DbPassword_MaxAttemptsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Attempts Exceeded.
        /// </summary>
        internal static string DbPassword_MaxAttemptsTitle {
            get {
                return ResourceManager.GetString("DbPassword_MaxAttemptsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter encryption password:.
        /// </summary>
        internal static string DbPassword_Prompt {
            get {
                return ResourceManager.GetString("DbPassword_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to try entering the password again?.
        /// </summary>
        internal static string DbPassword_RetryPrompt {
            get {
                return ResourceManager.GetString("DbPassword_RetryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Password.
        /// </summary>
        internal static string DbPassword_Title {
            get {
                return ResourceManager.GetString("DbPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect encryption password. Please try again..
        /// </summary>
        internal static string DbPassword_WrongPassword {
            get {
                return ResourceManager.GetString("DbPassword_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit exported..
        /// </summary>
        internal static string Export_AuditSaved {
            get {
                return ResourceManager.GetString("Export_AuditSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members exported..
        /// </summary>
        internal static string Export_MembersSaved {
            get {
                return ResourceManager.GetString("Export_MembersSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits exported..
        /// </summary>
        internal static string Export_VisitsSaved {
            get {
                return ResourceManager.GetString("Export_VisitsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default admin username: admin.
        /// </summary>
        internal static string FirstRun_AdminHint {
            get {
                return ResourceManager.GetString("FirstRun_AdminHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial admin username: admin.
        /// </summary>
        internal static string FirstRun_AdminLoginHint {
            get {
                return ResourceManager.GetString("FirstRun_AdminLoginHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin password.
        /// </summary>
        internal static string FirstRun_AdminPassword {
            get {
                return ResourceManager.GetString("FirstRun_AdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string FirstRun_Cancel {
            get {
                return ResourceManager.GetString("FirstRun_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required to open the databases. Keep it safe; cannot be reset..
        /// </summary>
        internal static string FirstRun_EncryptionHint {
            get {
                return ResourceManager.GetString("FirstRun_EncryptionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database encryption password.
        /// </summary>
        internal static string FirstRun_EncryptionPassword {
            get {
                return ResourceManager.GetString("FirstRun_EncryptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site code must be lowercase letters/numbers with dashes or underscores..
        /// </summary>
        internal static string FirstRun_InvalidSiteCode {
            get {
                return ResourceManager.GetString("FirstRun_InvalidSiteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary language.
        /// </summary>
        internal static string FirstRun_Language {
            get {
                return ResourceManager.GetString("FirstRun_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First run setup is required..
        /// </summary>
        internal static string FirstRun_Required {
            get {
                return ResourceManager.GetString("FirstRun_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site code, display name, admin password, and encryption password are required..
        /// </summary>
        internal static string FirstRun_RequiredFields {
            get {
                return ResourceManager.GetString("FirstRun_RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string FirstRun_Save {
            get {
                return ResourceManager.GetString("FirstRun_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site code.
        /// </summary>
        internal static string FirstRun_SiteCode {
            get {
                return ResourceManager.GetString("FirstRun_SiteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase, digits, dash/underscore allowed..
        /// </summary>
        internal static string FirstRun_SiteCodeHint {
            get {
                return ResourceManager.GetString("FirstRun_SiteCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site display name.
        /// </summary>
        internal static string FirstRun_SiteName {
            get {
                return ResourceManager.GetString("FirstRun_SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shown on title bar and badge; can include Greek..
        /// </summary>
        internal static string FirstRun_SiteNameHint {
            get {
                return ResourceManager.GetString("FirstRun_SiteNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First run setup.
        /// </summary>
        internal static string FirstRun_Title {
            get {
                return ResourceManager.GetString("FirstRun_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge expired on {0}..
        /// </summary>
        internal static string Gate_BadgeExpired {
            get {
                return ResourceManager.GetString("Gate_BadgeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge will expire on {0}..
        /// </summary>
        internal static string Gate_BadgeExpires {
            get {
                return ResourceManager.GetString("Gate_BadgeExpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid member number..
        /// </summary>
        internal static string Gate_InvalidMemberNumber {
            get {
                return ResourceManager.GetString("Gate_InvalidMemberNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last result.
        /// </summary>
        internal static string Gate_LastResult {
            get {
                return ResourceManager.GetString("Gate_LastResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log visit.
        /// </summary>
        internal static string Gate_LogButton {
            get {
                return ResourceManager.GetString("Gate_LogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to log visit: {0}.
        /// </summary>
        internal static string Gate_LogFailed {
            get {
                return ResourceManager.GetString("Gate_LogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged {0} {1} ({2})..
        /// </summary>
        internal static string Gate_LogSuccess {
            get {
                return ResourceManager.GetString("Gate_LogSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member not found or inactive..
        /// </summary>
        internal static string Gate_MemberNotFound {
            get {
                return ResourceManager.GetString("Gate_MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member number.
        /// </summary>
        internal static string Gate_MemberNumber {
            get {
                return ResourceManager.GetString("Gate_MemberNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        internal static string Gate_Mode_Entry {
            get {
                return ResourceManager.GetString("Gate_Mode_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Gate_Mode_Exit {
            get {
                return ResourceManager.GetString("Gate_Mode_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Gate_Notes {
            get {
                return ResourceManager.GetString("Gate_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Grid_Action {
            get {
                return ResourceManager.GetString("Grid_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business ID.
        /// </summary>
        internal static string Grid_BusinessIdNumber {
            get {
                return ResourceManager.GetString("Grid_BusinessIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Rank.
        /// </summary>
        internal static string Grid_BusinessRank {
            get {
                return ResourceManager.GetString("Grid_BusinessRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        internal static string Grid_Changes {
            get {
                return ResourceManager.GetString("Grid_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Grid_CreatedAt {
            get {
                return ResourceManager.GetString("Grid_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Grid_EntityId {
            get {
                return ResourceManager.GetString("Grid_EntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        internal static string Grid_EntityType {
            get {
                return ResourceManager.GetString("Grid_EntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Grid_FirstName {
            get {
                return ResourceManager.GetString("Grid_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Grid_Id {
            get {
                return ResourceManager.GetString("Grid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Grid_IsActive {
            get {
                return ResourceManager.GetString("Grid_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent.
        /// </summary>
        internal static string Grid_IsPermanent {
            get {
                return ResourceManager.GetString("Grid_IsPermanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Login.
        /// </summary>
        internal static string Grid_IsSharedLogin {
            get {
                return ResourceManager.GetString("Grid_IsSharedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login.
        /// </summary>
        internal static string Grid_LastLogin {
            get {
                return ResourceManager.GetString("Grid_LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Grid_LastName {
            get {
                return ResourceManager.GetString("Grid_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged By.
        /// </summary>
        internal static string Grid_LoggedBy {
            get {
                return ResourceManager.GetString("Grid_LoggedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID.
        /// </summary>
        internal static string Grid_MemberId {
            get {
                return ResourceManager.GetString("Grid_MemberId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member #.
        /// </summary>
        internal static string Grid_MemberNumber {
            get {
                return ResourceManager.GetString("Grid_MemberNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Type.
        /// </summary>
        internal static string Grid_MemberType {
            get {
                return ResourceManager.GetString("Grid_MemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type ID.
        /// </summary>
        internal static string Grid_MemberTypeId {
            get {
                return ResourceManager.GetString("Grid_MemberTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Grid_Notes {
            get {
                return ResourceManager.GetString("Grid_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string Grid_Office {
            get {
                return ResourceManager.GetString("Grid_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office ID.
        /// </summary>
        internal static string Grid_OfficeId {
            get {
                return ResourceManager.GetString("Grid_OfficeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal ID.
        /// </summary>
        internal static string Grid_PersonalIdNumber {
            get {
                return ResourceManager.GetString("Grid_PersonalIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string Grid_PhotoPath {
            get {
                return ResourceManager.GetString("Grid_PhotoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Grid_Role {
            get {
                return ResourceManager.GetString("Grid_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Grid_Timestamp {
            get {
                return ResourceManager.GetString("Grid_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string Grid_UpdatedAt {
            get {
                return ResourceManager.GetString("Grid_UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string Grid_UserId {
            get {
                return ResourceManager.GetString("Grid_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Grid_Username {
            get {
                return ResourceManager.GetString("Grid_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Grid_VisitType {
            get {
                return ResourceManager.GetString("Grid_VisitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user: {0}.
        /// </summary>
        internal static string Lock_CurrentUser {
            get {
                return ResourceManager.GetString("Lock_CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials..
        /// </summary>
        internal static string Lock_InvalidCredentials {
            get {
                return ResourceManager.GetString("Lock_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user is currently signed in..
        /// </summary>
        internal static string Lock_NoUser {
            get {
                return ResourceManager.GetString("Lock_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session locked. Enter password or quick code..
        /// </summary>
        internal static string Lock_Prompt {
            get {
                return ResourceManager.GetString("Lock_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch user was cancelled or failed..
        /// </summary>
        internal static string Lock_SwitchUserFailed {
            get {
                return ResourceManager.GetString("Lock_SwitchUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        internal static string Login_Failed {
            get {
                return ResourceManager.GetString("Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick code.
        /// </summary>
        internal static string Login_QuickCode {
            get {
                return ResourceManager.GetString("Login_QuickCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Main_Welcome {
            get {
                return ResourceManager.GetString("Main_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business ID.
        /// </summary>
        internal static string Member_BusinessId {
            get {
                return ResourceManager.GetString("Member_BusinessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Rank.
        /// </summary>
        internal static string Member_BusinessRank {
            get {
                return ResourceManager.GetString("Member_BusinessRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Photo.
        /// </summary>
        internal static string Member_ClearPhoto {
            get {
                return ResourceManager.GetString("Member_ClearPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this member?.
        /// </summary>
        internal static string Member_DeleteConfirm {
            get {
                return ResourceManager.GetString("Member_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete member.
        /// </summary>
        internal static string Member_DeleteFailed {
            get {
                return ResourceManager.GetString("Member_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member deleted successfully..
        /// </summary>
        internal static string Member_DeleteSuccess {
            get {
                return ResourceManager.GetString("Member_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Member_FirstName {
            get {
                return ResourceManager.GetString("Member_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Member_LastName {
            get {
                return ResourceManager.GetString("Member_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Number.
        /// </summary>
        internal static string Member_Number {
            get {
                return ResourceManager.GetString("Member_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member number is required..
        /// </summary>
        internal static string Member_NumberRequired {
            get {
                return ResourceManager.GetString("Member_NumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string Member_Office {
            get {
                return ResourceManager.GetString("Member_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Staff.
        /// </summary>
        internal static string Member_PermanentStaff {
            get {
                return ResourceManager.GetString("Member_PermanentStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal ID.
        /// </summary>
        internal static string Member_PersonalId {
            get {
                return ResourceManager.GetString("Member_PersonalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save member.
        /// </summary>
        internal static string Member_SaveFailed {
            get {
                return ResourceManager.GetString("Member_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member saved successfully..
        /// </summary>
        internal static string Member_SaveSuccess {
            get {
                return ResourceManager.GetString("Member_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Type.
        /// </summary>
        internal static string Member_Type {
            get {
                return ResourceManager.GetString("Member_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member number must be numeric..
        /// </summary>
        internal static string Members_NumberInvalid {
            get {
                return ResourceManager.GetString("Members_NumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a member first..
        /// </summary>
        internal static string Members_SelectFirst {
            get {
                return ResourceManager.GetString("Members_SelectFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.jpg;*.jpeg;*.png.
        /// </summary>
        internal static string Photo_Filter {
            get {
                return ResourceManager.GetString("Photo_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photo.
        /// </summary>
        internal static string Photo_None {
            get {
                return ResourceManager.GetString("Photo_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Photo.
        /// </summary>
        internal static string Photo_SelectTitle {
            get {
                return ResourceManager.GetString("Photo_SelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick code must be 4-6 digits (0-9 only).
        /// </summary>
        internal static string QuickCode_Hint {
            get {
                return ResourceManager.GetString("QuickCode_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved..
        /// </summary>
        internal static string Settings_Saved {
            get {
                return ResourceManager.GetString("Settings_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download visits database..
        /// </summary>
        internal static string Sync_DownloadFailed {
            get {
                return ResourceManager.GetString("Sync_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include photos.
        /// </summary>
        internal static string Sync_IncludePhotos {
            get {
                return ResourceManager.GetString("Sync_IncludePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site: {0} ({1})
        ///Members: {2}
        ///Visits: {3}
        ///Last visit: {4}.
        /// </summary>
        internal static string Sync_InfoDetails {
            get {
                return ResourceManager.GetString("Sync_InfoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote info received..
        /// </summary>
        internal static string Sync_InfoReceived {
            get {
                return ResourceManager.GetString("Sync_InfoReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master database updated..
        /// </summary>
        internal static string Sync_MasterImported {
            get {
                return ResourceManager.GetString("Sync_MasterImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master database not found..
        /// </summary>
        internal static string Sync_MasterMissing {
            get {
                return ResourceManager.GetString("Sync_MasterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master overwritten..
        /// </summary>
        internal static string Sync_MasterOverwritten {
            get {
                return ResourceManager.GetString("Sync_MasterOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped (newer local) - Offices: {0}, MemberTypes: {1}, Members: {2}.
        /// </summary>
        internal static string Sync_MergeConflicts {
            get {
                return ResourceManager.GetString("Sync_MergeConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members skipped: {0}.
        /// </summary>
        internal static string Sync_MergeConflictsMembers {
            get {
                return ResourceManager.GetString("Sync_MergeConflictsMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offices skipped: {0}.
        /// </summary>
        internal static string Sync_MergeConflictsOffices {
            get {
                return ResourceManager.GetString("Sync_MergeConflictsOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberTypes skipped: {0}.
        /// </summary>
        internal static string Sync_MergeConflictsTypes {
            get {
                return ResourceManager.GetString("Sync_MergeConflictsTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge applied. Offices +{0}/{1}, MemberTypes +{2}/{3}, Members +{4}/{5}.
        /// </summary>
        internal static string Sync_MergeSummary {
            get {
                return ResourceManager.GetString("Sync_MergeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite local visits database?.
        /// </summary>
        internal static string Sync_OverwriteVisitsConfirm {
            get {
                return ResourceManager.GetString("Sync_OverwriteVisitsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes = merge remote into local, No = overwrite. Cancel to abort..
        /// </summary>
        internal static string Sync_PullConfirm {
            get {
                return ResourceManager.GetString("Sync_PullConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull master.
        /// </summary>
        internal static string Sync_PullMaster {
            get {
                return ResourceManager.GetString("Sync_PullMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull visits db.
        /// </summary>
        internal static string Sync_PullVisits {
            get {
                return ResourceManager.GetString("Sync_PullVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload master data..
        /// </summary>
        internal static string Sync_PushFailed {
            get {
                return ResourceManager.GetString("Sync_PushFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push master.
        /// </summary>
        internal static string Sync_PushMaster {
            get {
                return ResourceManager.GetString("Sync_PushMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master data uploaded..
        /// </summary>
        internal static string Sync_PushSuccess {
            get {
                return ResourceManager.GetString("Sync_PushSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent events.
        /// </summary>
        internal static string Sync_RecentEvents {
            get {
                return ResourceManager.GetString("Sync_RecentEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Sync_Status {
            get {
                return ResourceManager.GetString("Sync_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received {0} visits..
        /// </summary>
        internal static string Sync_VisitsCountLabel {
            get {
                return ResourceManager.GetString("Sync_VisitsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits database updated..
        /// </summary>
        internal static string Sync_VisitsImported {
            get {
                return ResourceManager.GetString("Sync_VisitsImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits received:.
        /// </summary>
        internal static string Sync_VisitsReceived {
            get {
                return ResourceManager.GetString("Sync_VisitsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits received: {0}.
        /// </summary>
        internal static string Sync_VisitsReceivedCount {
            get {
                return ResourceManager.GetString("Sync_VisitsReceivedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        internal static string Tab_Audit {
            get {
                return ResourceManager.GetString("Tab_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gate.
        /// </summary>
        internal static string Tab_Gate {
            get {
                return ResourceManager.GetString("Tab_Gate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string Tab_Members {
            get {
                return ResourceManager.GetString("Tab_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Tab_Settings {
            get {
                return ResourceManager.GetString("Tab_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Tab_Users {
            get {
                return ResourceManager.GetString("Tab_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        internal static string Tab_Visits {
            get {
                return ResourceManager.GetString("Tab_Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete system users..
        /// </summary>
        internal static string User_CannotDeleteSystem {
            get {
                return ResourceManager.GetString("User_CannotDeleteSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete user.
        /// </summary>
        internal static string User_DeleteFailed {
            get {
                return ResourceManager.GetString("User_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully..
        /// </summary>
        internal static string User_DeleteSuccess {
            get {
                return ResourceManager.GetString("User_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save user.
        /// </summary>
        internal static string User_SaveFailed {
            get {
                return ResourceManager.GetString("User_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User saved successfully..
        /// </summary>
        internal static string User_SaveSuccess {
            get {
                return ResourceManager.GetString("User_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only admins can manage users..
        /// </summary>
        internal static string Users_AdminOnly {
            get {
                return ResourceManager.GetString("Users_AdminOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate this user?.
        /// </summary>
        internal static string Users_DeactivateConfirm {
            get {
                return ResourceManager.GetString("Users_DeactivateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this user?.
        /// </summary>
        internal static string Users_DeleteConfirm {
            get {
                return ResourceManager.GetString("Users_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string Users_FirstName {
            get {
                return ResourceManager.GetString("Users_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Users_IsActive {
            get {
                return ResourceManager.GetString("Users_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared gate account.
        /// </summary>
        internal static string Users_IsShared {
            get {
                return ResourceManager.GetString("Users_IsShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Users_LastName {
            get {
                return ResourceManager.GetString("Users_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Users_Password {
            get {
                return ResourceManager.GetString("Users_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required for new users..
        /// </summary>
        internal static string Users_PasswordRequired {
            get {
                return ResourceManager.GetString("Users_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated..
        /// </summary>
        internal static string Users_PasswordUpdated {
            get {
                return ResourceManager.GetString("Users_PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickCode is not allowed for admins..
        /// </summary>
        internal static string Users_QuickCodeNotAllowed {
            get {
                return ResourceManager.GetString("Users_QuickCodeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick code updated..
        /// </summary>
        internal static string Users_QuickCodeUpdated {
            get {
                return ResourceManager.GetString("Users_QuickCodeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password for user:.
        /// </summary>
        internal static string Users_ResetPasswordPrompt {
            get {
                return ResourceManager.GetString("Users_ResetPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new quick code (4-6 digits, leave blank to clear):.
        /// </summary>
        internal static string Users_ResetQuickCodePrompt {
            get {
                return ResourceManager.GetString("Users_ResetQuickCodePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Users_Role {
            get {
                return ResourceManager.GetString("Users_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a user first..
        /// </summary>
        internal static string Users_SelectUser {
            get {
                return ResourceManager.GetString("Users_SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Users_Username {
            get {
                return ResourceManager.GetString("Users_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        internal static string Users_UsernameRequired {
            get {
                return ResourceManager.GetString("Users_UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update notes:.
        /// </summary>
        internal static string Visits_UpdateNotesPrompt {
            get {
                return ResourceManager.GetString("Visits_UpdateNotesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Visits_UpdateNotesTitle {
            get {
                return ResourceManager.GetString("Visits_UpdateNotesTitle", resourceCulture);
            }
        }
    }
}
